site_name: Python Flow SDK
theme: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: True
            show_root_full_path: False
            show_if_no_docstring: True
            show_signature_annotations: True
            heading_level: 3

nav:
  - Overview: python_SDK_guide.md
  - 'Running Examples': examples.md
  - 'API Docs':
      - Client: api_docs/client.md
      - Signer: api_docs/signer.md
      - Keys: api_docs/keys.md
  - Contributing: contributing.md
  - Roadmap: roadmap.md

markdown_extensions:
  - toc:
      permalink: True
      